
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    session:
        handler_id: ~
#        handler_id: null
#        cookie_secure: auto
#        cookie_samesite: lax
    property_info:
        enabled: true
    #esi: true
    #fragments: true
    php_errors:
        log: true
